name: Build and Publish Docker Images Prod

on:
    push:
        branches: master

jobs:
    worksuite-api:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Free disk space
              run: |
                df -h /
                sudo swapoff -a
                sudo apt clean
                docker image ls -aq
                docker rmi $(docker image ls -aq)
                find ~/work/_temp -name "cache.tgz" -exec rm -f {} \;
                sudo rm -rf "/usr/local/share/boost"
                sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                df -h /

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GH_TOKEN }}



            - name: Build
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./.deploy/api/Dockerfile
                  load: true
                  platforms: linux/amd64
                  tags: |
                      ghcr.io/worksuiteio/worksuite-api:latest
                      worksuiteio/worksuite-api:latest

                  cache-from: type=registry,ref=worksuiteio/worksuite-api:latest
                  cache-to: type=inline

            - name: Docker images list
              run: |
                 sudo docker image list

            - name: Push to Docker Hub Registry
              run: |
                  docker push worksuiteio/worksuite-api:latest



            - name: Push to Github Registry
              run: |
                  docker push ghcr.io/worksuiteio/worksuite-api:latest

    worksuite-webapp:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Free disk space
              run: |
                df -h /
                sudo swapoff -a
                sudo apt clean
                docker image ls -aq
                docker rmi $(docker image ls -aq)
                find ~/work/_temp -name "cache.tgz" -exec rm -f {} \;
                sudo rm -rf "/usr/local/share/boost"
                sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                df -h /

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GH_TOKEN }}


            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./.deploy/webapp/Dockerfile
                  load: true
                  tags: |
                      ghcr.io/worksuiteio/worksuite-webapp:latest
                      worksuiteio/worksuite-webapp:latest

                  cache-from: type=registry,ref=worksuiteio/worksuite-webapp:latest
                  cache-to: type=inline

            - name: Push to Docker Hub Registry
              run: |
                  docker push worksuiteio/worksuite-webapp:latest



            - name: Push to Github Registry
              run: |
                  docker push ghcr.io/worksuiteio/worksuite-webapp:latest
